version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.antlr:antlr4
    versions:
    - 4.9.1
  - dependency-name: com.google.guava:guava
    versions:
    - 30.1-jre
